#!/bin/bash

# a grid search

# kList=(2 5 10 20 50 100 200)

# search
kaList=(2 5 10 20 50 100 200)
kaList+=(15 25 30 35 40 45 500)
kaList+=(3 4 6 7 8 9 75 300 400)
echo ${kaList[@]}


date="200807" # depends on the input, which was from this date
subsample_frac=0.8
subsample_times=10

for ka in ${kaList[@]}; do
	knn=$ka
		echo $ka, $k

		# # prep config file
		# output="config_mc_mc_ka${ka}_knn${k}_${date}.py"
		# cp config_template_mc_mc_ka_knn.py $output 
		# sed -i "s/knn = TOBEFILLED/knn = ${knn}/g" $output 
		# sed -i "s/ka_smooth = TOBEFILLED/ka_smooth = ${ka}/g" $output 
		# sed -i "s/date = TOBEFILLED/date = ${date}/g" $output 

		# # run SCF (with 80% of cells, repeat n times)
		# /cndd2/fangming/projects/SCF_package/SingleCellFusion/scripts/SCF_main_repeat_subsampling.py \
		# 	-c $output \
		# 	-s ${subsample_frac} \
		# 	-sn ${subsample_times}


		# use the ones (knn_xx) already generated by cross-modality studies
		for (( i=0; i<${subsample_times}; i++ )) do
			# # run corr analysis
			echo $i
			../correlation_analysis_celllevel_withinmod-v3-stage3.py -ka $ka -knn $knn -dt $date -isub $i
			# break
		done

done